server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api {
     #   proxy_pass http://backend:5000;    #use this for docker-compose setup for Ec2 instances or the actual setup not codespaces setup
        proxy_pass http://localhost:5000;   # use this for local development and codespaces setup
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}