services:
   frontend:
     build: ./frontend
     container_name: frontend
     ports:
      - "3000:80"
      - "3001:3001"
     depends_on:
      - backend
     networks:
       - ecommerce-network
     restart: unless-stopped
   
   backend:  
     build: ./backend
     container_name: backend
     ports:
      - "5000:5000"
     networks:
       - ecommerce-network
     restart: unless-stopped
     environment:
      - MONGO_URI=mongodb://mongo:27017/ecommerce
     depends_on:
      - mongo
   mongo:
     image: mongo:6
     container_name: mongo
     ports:
      - "27017:27017"
     networks:
       - ecommerce-network
     restart: unless-stopped
     volumes:
      - mongo-data:/data/db
   networks:
     ecommerce-network:
       driver: bridge
   volumes:
      mongo-data:           
      