receivers:
  filelog:
    include:
      - /var/lib/docker/containers/*/*.log

processors:
  batch:

exporters:
  loki:
    endpoint: http://loki:3100/loki/api/v1/push

service:
  pipelines:
    logs:
      receivers: [filelog]
      processors: [batch]
      exporters: [loki]